language: csharp
solution: Easly-Language.sln

before_script:
  - wget https://github.com/bmuschko/link-verifier/releases/download/v0.7/link-verifier-0.7-linux-amd64.tar.gz -O /tmp/link-verifier.tar.gz
  - tar -xvf /tmp/link-verifier.tar.gz
  - export PATH=$PATH:$PWD/link-verifier/

script:
- ./link-verifier | grep FAILED
- echo "${PIPESTATUS[1]} ${PIPESTATUS[2]}"
- msbuild Easly-Language.sln /p:Configuration=Travis

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./Easly-Language/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master

